/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage;

import java.awt.Color;
import java.awt.Font;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import tablepackage.TableAvailabilityHours;
import tablepackage.TableCompetenzeAttività;
import tablepackage.TableMaintenanceActivities;

/**
 *
 * @author 39392
 */
public class GuiMaintenanceAssigmentStep4 extends javax.swing.JFrame {

    private String mantainer;
    private int day;
    private String skills;
    private DefaultTableModel model;
    private TableMaintenanceActivities maintenanceActivities;
    private TableCompetenzeAttività competenzeAttività;
    private TableAvailabilityHours availabilityHours;
    private int week;
    
    public GuiMaintenanceAssigmentStep4(Statement st, String id, String mantainer, int day, String skills, int week) {
        initComponents(); 
        this.day=day;
        this.mantainer=mantainer;
        this.skills=skills;
        this.week=week;
        model=(DefaultTableModel)availabilityTable2.getModel();
        maintenanceActivities= new TableMaintenanceActivities(st);
        competenzeAttività= new TableCompetenzeAttività(st);
        availabilityHours=new TableAvailabilityHours(st);
        activityDataTextField.setText(""+day);
        visualizeWeekTextField(id);
        visualizeInActivityDataTextField(id);
        visualizeDay();
        visualizeMantainerTextField();
        visualizeInTable(id);
        setTableDesig();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        weekTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        dayLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        activityDataTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        maintenanceAvailabilityLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availabilityTable2 = new javax.swing.JTable();
        sendButton = new javax.swing.JButton();
        dayTextField1 = new javax.swing.JTextField();

        setTitle("MAINTENACE ASSIGMENT");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(162, 197, 220));
        jPanel1.setToolTipText("");

        jPanel.setBackground(new java.awt.Color(141, 199, 228));
        jPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 64, 82));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Week n°");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(141, 199, 228));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(27, 64, 82));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Activity to assign");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        weekTextField.setEditable(false);
        weekTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(141, 199, 228));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dayLabel.setBackground(new java.awt.Color(255, 255, 255));
        dayLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dayLabel.setForeground(new java.awt.Color(27, 64, 82));
        dayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dayTextField.setEditable(false);
        dayTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });

        activityDataTextField.setEditable(false);
        activityDataTextField.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        activityDataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityDataTextFieldActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(141, 199, 228));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        maintenanceAvailabilityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maintenanceAvailabilityLabel.setForeground(new java.awt.Color(27, 64, 82));
        maintenanceAvailabilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintenanceAvailabilityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintenanceAvailabilityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        availabilityTable2.setBackground(new java.awt.Color(213, 234, 255));
        availabilityTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        availabilityTable2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        availabilityTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maintainer", "Skills", "Av.8.00-9.00", "Av.9.00-10.00", "Av.10.00-11.00", "Av.11.00-12.00", "Av.14.00-15.00", "Av.15.00-16.00", "Av.16.00-17.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        availabilityTable2.setAutoscrolls(false);
        availabilityTable2.setColumnSelectionAllowed(true);
        availabilityTable2.setShowVerticalLines(false);
        jScrollPane1.setViewportView(availabilityTable2);
        if (availabilityTable2.getColumnModel().getColumnCount() > 0) {
            availabilityTable2.getColumnModel().getColumn(0).setMinWidth(100);
            availabilityTable2.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        sendButton.setBackground(new java.awt.Color(141, 199, 228));
        sendButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sendButton.setForeground(new java.awt.Color(34, 102, 136));
        sendButton.setText("SEND");
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        dayTextField1.setEditable(false);
        dayTextField1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        dayTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(dayTextField1))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1368, 1368, 1368)
                                .addComponent(weekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activityDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1181, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(weekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayTextField1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(activityDataTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendButton)
                .addGap(128, 128, 128))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
   
    }//GEN-LAST:event_sendButtonMouseClicked

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void dayTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextField1ActionPerformed

    private void activityDataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityDataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activityDataTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceAssigmentStep4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceAssigmentStep4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceAssigmentStep4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceAssigmentStep4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiMaintenanceAssigmentStep3(st).setVisible(true);
            }
        });
    }
   private void visualizeWeekTextField(String idActivity){
    int week ;
    week=maintenanceActivities.getWeekActivity(idActivity);
    dayTextField.setText(" "+week);
    
}
   private String getDay(){
      switch (day){
		case 1: 
                    return "Monday";
		 
		case 2: 
                    return "Tuesday";
		
		case 3: 
                    return "Wednesday";
		
		case 4: 
                    return "Thursday";
		
                case 5: 
                    return "Friday";
		
                case 6: 
                    return "Saturday";
		
                case 7: 
                    return "Sunday";
		
    } 
      return "";
   }
   
   private void visualizeDay(){
    String dayS=getDay();
    dayLabel.setText(dayS);
    Calendar cal = Calendar.getInstance();
    cal.set(Calendar.YEAR, 2021);
    cal.set(Calendar.WEEK_OF_YEAR, week);
    cal.set(Calendar.DAY_OF_WEEK,day+1);
    int day =cal.get(Calendar.DAY_OF_WEEK_IN_MONTH);
    int ordinalDay = cal.get(Calendar.DAY_OF_YEAR);
    dayTextField1.setText(""+day);
}
   
   
   private void visualizeInActivityDataTextField(String idActivity){
        String data = new String();
        data=maintenanceActivities.visualizeActivity2(idActivity);
        activityDataTextField.setText(data);
    }
   
   private void visualizeMantainerTextField(){
    maintenanceAvailabilityLabel.setText("AVAILABILITY "+mantainer.toUpperCase());
}
   
   private void visualizeInTable(String idActivity){
      ArrayList <ArrayList> items=new ArrayList();
      String dayS=getDay();
      int selectedWeek=maintenanceActivities.getWeekActivity(idActivity);
      items=availabilityHours.visualize(""+selectedWeek, dayS, mantainer);
      for (ArrayList k : items){
        model.insertRow(model.getRowCount(),new Object[]{mantainer, skills, k.get(0).toString()+" min" ,k.get(1).toString()+" min",k.get(2).toString()+" min", k.get(3).toString()+" min",k.get(4).toString()+" min", k.get(5).toString()+" min", k.get(6).toString()+" min"});
      }   
 }
     //213,234,255
    private void setTableDesig(){
      availabilityTable2.getTableHeader().setBackground(new Color(141,199,228));
      availabilityTable2.getTableHeader().setForeground(new Color(27,64,82));
      availabilityTable2.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,12));
      availabilityTable2.getTableHeader().setOpaque(false);
      availabilityTable2.setRowHeight(26);
 }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activityDataTextField;
    private javax.swing.JTable availabilityTable2;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JTextField dayTextField1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maintenanceAvailabilityLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField weekTextField;
    // End of variables declaration//GEN-END:variables
}
