package guipackage;


import java.awt.Color;
import java.awt.Font;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tablepackage.TableMaintenanceActivities;
import tablepackage.TableSite;
import tablepackage.TableType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    
/**
 *
 * @author 39392
 */
public class GuiMaintenanceManagement extends javax.swing.JFrame {
    private Statement st;
    private DefaultTableModel model;
    private TableMaintenanceActivities maintenanceActivities;
    
    public GuiMaintenanceManagement(Statement st) {
        initComponents();
        this.st=st;
        maintenanceActivities= new TableMaintenanceActivities(st);
        model=(DefaultTableModel) maintenanceTable.getModel();
        visualizeInTable();
        visualizeSiteInCombo();
        visualizeTypeInCombo();
        visualizeWeekInCombo();
        setTableDesig();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        manutTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        maintenanceTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        weekComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        typeOfMainanceComboBox = new javax.swing.JComboBox<>();
        estimatedTimeSpinner = new javax.swing.JSpinner();
        siteComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();

        manutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "AREA", "TYPE", "Estimated intervention time [min]"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(manutTable);

        setTitle("MAINTENANCE MANAGEMENT");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(162, 197, 220));

        addButton.setBackground(new java.awt.Color(141, 199, 228));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addButton.setForeground(new java.awt.Color(34, 102, 136));
        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(141, 199, 228));
        removeButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        removeButton.setForeground(new java.awt.Color(34, 102, 136));
        removeButton.setText("Remove");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(141, 199, 228));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updateButton.setForeground(new java.awt.Color(34, 102, 136));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        maintenanceTable.setBackground(new java.awt.Color(213, 234, 255));
        maintenanceTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maintenanceTable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        maintenanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TYPOLOGY OF MAINTENANCE", "TYPE", "AREA", "WEEK", "ESTIMATED INTERVENTION TIME [min]", "INTERRUPTIBLE ACTIVITY", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        maintenanceTable.setToolTipText("");
        maintenanceTable.setShowVerticalLines(false);
        maintenanceTable.getTableHeader().setReorderingAllowed(false);
        maintenanceTable.setVerifyInputWhenFocusTarget(false);
        maintenanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintenanceTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(maintenanceTable);
        if (maintenanceTable.getColumnModel().getColumnCount() > 0) {
            maintenanceTable.getColumnModel().getColumn(0).setMinWidth(60);
            maintenanceTable.getColumnModel().getColumn(0).setMaxWidth(60);
            maintenanceTable.getColumnModel().getColumn(1).setMinWidth(230);
            maintenanceTable.getColumnModel().getColumn(1).setMaxWidth(230);
            maintenanceTable.getColumnModel().getColumn(2).setMinWidth(130);
            maintenanceTable.getColumnModel().getColumn(2).setMaxWidth(130);
            maintenanceTable.getColumnModel().getColumn(3).setMinWidth(120);
            maintenanceTable.getColumnModel().getColumn(3).setMaxWidth(120);
            maintenanceTable.getColumnModel().getColumn(4).setMinWidth(60);
            maintenanceTable.getColumnModel().getColumn(4).setMaxWidth(60);
            maintenanceTable.getColumnModel().getColumn(5).setMinWidth(270);
            maintenanceTable.getColumnModel().getColumn(5).setMaxWidth(270);
            maintenanceTable.getColumnModel().getColumn(6).setMinWidth(190);
            maintenanceTable.getColumnModel().getColumn(6).setMaxWidth(190);
            maintenanceTable.getColumnModel().getColumn(7).setMinWidth(180);
            maintenanceTable.getColumnModel().getColumn(7).setMaxWidth(180);
        }
        maintenanceTable.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 64, 82));
        jLabel3.setText("ID:");

        idTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 64, 82));
        jLabel4.setText("AREA:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 64, 82));
        jLabel5.setText("TYPE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 64, 82));
        jLabel6.setText("ESTIMATED INTERVENTION TIME [min]:");

        typeComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-- Select one type --]" }));

        yesRadioButton.setBackground(new java.awt.Color(162, 197, 220));
        yesRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yesRadioButton.setText("Yes");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadioButtonActionPerformed(evt);
            }
        });

        noRadioButton.setBackground(new java.awt.Color(162, 197, 220));
        noRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noRadioButton.setText("No");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 64, 82));
        jLabel1.setText("INTERRUPTIBLE ACTIVITY:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 64, 82));
        jLabel7.setText("WEEK:");

        weekComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-- Select one week --]" }));
        weekComboBox.setToolTipText("");
        weekComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 64, 82));
        jLabel8.setText("TYPOLOGY:");

        typeOfMainanceComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeOfMainanceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-- Select one typology --]", "Planned activity", "Un-planned activity (EWO)", "Extra activity (unplanned activity)" }));

        estimatedTimeSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        estimatedTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        siteComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        siteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-- Select one site --]" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 64, 82));
        jLabel2.setText("ACTIVITY DESCRIPTION:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(3);
        descriptionTextArea.setTabSize(5);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(estimatedTimeSpinner)
                                            .addComponent(siteComboBox, 0, 187, Short.MAX_VALUE))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(weekComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(typeOfMainanceComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yesRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descriptionScrollPane)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(typeOfMainanceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(estimatedTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(descriptionScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(updateButton))
                .addGap(25, 25, 25))
        );

        weekComboBox.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void weekComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weekComboBoxActionPerformed

    private void yesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadioButtonActionPerformed
        if(yesRadioButton.isSelected()){
          noRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_yesRadioButtonActionPerformed

    private void noRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadioButtonActionPerformed
      if(noRadioButton.isSelected()){
         yesRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_noRadioButtonActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        String id=idTextField.getText();
        String typeOfMainance=typeOfMainanceComboBox.getSelectedItem().toString(); 
        String type= typeComboBox.getSelectedItem().toString();
        String area=siteComboBox.getSelectedItem().toString();
        String week=weekComboBox.getSelectedItem().toString();
        String interruptibleActivity=selectedRadioButton();
        Object estimatedTime= estimatedTimeSpinner.getValue();
        String description=descriptionTextArea.getText();
           
        if(id.equals("") || typeOfMainanceComboBox.getSelectedIndex()==0 || typeComboBox.getSelectedIndex()==0 || siteComboBox.getSelectedIndex()==0|| weekComboBox.getSelectedIndex()==0 || interruptibleActivity.equals("") || descriptionTextArea.equals(""))
            JOptionPane.showMessageDialog(this, "Plase enter all data.","ERROR",JOptionPane.ERROR_MESSAGE); 
        else{
        if(checkId()){
        model.insertRow(model.getRowCount(),new Object[]{id, typeOfMainance, type,area, week, estimatedTime, interruptibleActivity, description});
        maintenanceActivities.insert(id, typeOfMainance, type, area, week, estimatedTime, interruptibleActivity, description);
        resetFields();
        }else{
           JOptionPane.showMessageDialog(this, "Plase specify another id.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
       }
    }//GEN-LAST:event_addButtonMouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
      try{
       String id=model.getValueAt(maintenanceTable.getSelectedRow(), 0).toString();
       maintenanceActivities.delete(id);
       model.removeRow(maintenanceTable.getSelectedRow());
       resetFields();
       }catch(java.lang.ArrayIndexOutOfBoundsException ex){
        JOptionPane.showMessageDialog(this, "Plase select one row.","ERROR",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_removeButtonMouseClicked

    private void maintenanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceTableMouseClicked
        resetFields();
        visualizeFields();
    }//GEN-LAST:event_maintenanceTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
     try{
     String oldId=model.getValueAt(maintenanceTable.getSelectedRow(), 0).toString();
     String id=idTextField.getText();
     String typologyOfMaintenance= typeOfMainanceComboBox.getSelectedItem().toString();
     String type=typeComboBox.getSelectedItem().toString();
     String area=siteComboBox.getSelectedItem().toString();
     String week= weekComboBox.getSelectedItem().toString(); 
     Object estimatedTime=estimatedTimeSpinner.getValue();
     String interruptibleActivity=selectedRadioButton();
     String description=descriptionTextArea.getText();
     if(maintenanceTable.getSelectedRowCount()==1){
           if(checkId() ||  model.getValueAt(maintenanceTable.getSelectedRow(), 0).toString().equals(idTextField.getText())){
               maintenanceActivities.update(oldId, id, typologyOfMaintenance, type, area, week, estimatedTime, interruptibleActivity, description);
               model.setValueAt(id, maintenanceTable.getSelectedRow(),0);
               model.setValueAt(typologyOfMaintenance, maintenanceTable.getSelectedRow(),1);
               model.setValueAt(type, maintenanceTable.getSelectedRow(),2);
               model.setValueAt(area, maintenanceTable.getSelectedRow(),3);
               model.setValueAt(week, maintenanceTable.getSelectedRow(),4);
               model.setValueAt(estimatedTime, maintenanceTable.getSelectedRow(),5);
               model.setValueAt(interruptibleActivity, maintenanceTable.getSelectedRow(),6);
               model.setValueAt(description, maintenanceTable.getSelectedRow(),7);
               JOptionPane.showMessageDialog(this, "Update successfully", "INFORMATION MESSAGE", JOptionPane.INFORMATION_MESSAGE);
               resetFields();
           }else{
               JOptionPane.showMessageDialog(this, "Plase specify another id.","ERROR",JOptionPane.ERROR_MESSAGE);
           }
      }else{
          JOptionPane.showMessageDialog(this, "Plase select single row for update.","ERROR",JOptionPane.ERROR_MESSAGE);    
       }
     }catch(java.lang.ArrayIndexOutOfBoundsException ex){
        JOptionPane.showMessageDialog(this, "Plase select one row.","ERROR",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updateButtonActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMaintenanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //new GuiMaintenanceManagement().setVisible(true);
            }
        });
    }
    
 private void visualizeTypeInCombo(){  
      TableType typology=new TableType(this.st);;
      ArrayList <String> items=new ArrayList();
      items=typology.visualize();
      for (String k : items){
          typeComboBox.addItem(k);
      }
}
 
  private void visualizeSiteInCombo(){  
      TableSite sites=new TableSite(this.st);;
      ArrayList <String> items=new ArrayList();
      items=sites.visualize();
      for (String k : items){
          siteComboBox.addItem(k);
      }
}
 private void visualizeWeekInCombo(){  
   for(int i=1; i<53; i++){
      weekComboBox.addItem(""+i);
   }
}
  private void visualizeInTable(){
      ArrayList <ArrayList> items=new ArrayList();
      items=maintenanceActivities.visualize();
      for (ArrayList k : items){
        model.insertRow(model.getRowCount(),new Object[]{k.get(0).toString(),k.get(1).toString(),k.get(2).toString(), k.get(3).toString(), k.get(4).toString(), k.get(5), k.get(6).toString(), k.get(7) });
      }
 }
  
 private String selectedRadioButton(){
  if(yesRadioButton.isSelected())
    return "Yes";
   if(noRadioButton.isSelected())
    return "No";
   return "";
}
 private void resetFields(){
   idTextField.setText("");
   typeOfMainanceComboBox.setSelectedIndex(0); 
   typeComboBox.setSelectedIndex(0);
   siteComboBox.setSelectedIndex(0);
   weekComboBox.setSelectedIndex(0);
   yesRadioButton.setSelected(false);
   noRadioButton.setSelected(false);
   estimatedTimeSpinner.setValue(1);
   descriptionTextArea.setText("");
 }
 
 private boolean checkId(){
     //ritorna true se l'id non è già presente nella tabella, false altrimenti.
     for(int i=0; i<model.getRowCount(); i++){
         //in getValue i è la riga, 0 è la colonna
         if(idTextField.getText().equals(model.getValueAt(i, 0).toString())){
             return false;
        }
     }
     return true;
 }
 private void visualizeFields(){
    String id=model.getValueAt(maintenanceTable.getSelectedRow(), 0).toString();
    String typologyOfMaintenance=model.getValueAt(maintenanceTable.getSelectedRow(), 1).toString();
    String type=model.getValueAt(maintenanceTable.getSelectedRow(), 2).toString();
    String area=model.getValueAt(maintenanceTable.getSelectedRow(), 3).toString();
    String week=model.getValueAt(maintenanceTable.getSelectedRow(), 4).toString();
    Object estimatedTime=model.getValueAt(maintenanceTable.getSelectedRow(), 5);
    String interruptibleActivity=model.getValueAt(maintenanceTable.getSelectedRow(), 6).toString();
    String description=model.getValueAt(maintenanceTable.getSelectedRow(), 7).toString();
   // String description=
    idTextField.setText(id);
    typeOfMainanceComboBox.setSelectedItem(typologyOfMaintenance);
    typeComboBox.setSelectedItem(type);
    siteComboBox.setSelectedItem(area);
    weekComboBox.setSelectedItem(week);
    estimatedTimeSpinner.setValue(estimatedTime);
    if(interruptibleActivity.equals("Yes"))
        yesRadioButton.setSelected(true);
    else
        noRadioButton.setSelected(true);
    descriptionTextArea.setText(description);
}
      private void setTableDesig(){
      maintenanceTable.getTableHeader().setBackground(new Color(141,199,228));
      maintenanceTable.getTableHeader().setForeground(new Color(27,64,82));
      maintenanceTable.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,12));
      maintenanceTable.getTableHeader().setOpaque(false);
      maintenanceTable.setRowHeight(20);
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JSpinner estimatedTimeSpinner;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable maintenanceTable;
    private javax.swing.JTable manutTable;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JComboBox<String> siteComboBox;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JComboBox<String> typeOfMainanceComboBox;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> weekComboBox;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
