/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage;

import java.sql.Statement;
import javax.swing.JOptionPane;
import tablepackage.TableCompetencies;
import tablepackage.TableProcedure;
import tablepackage.TableProcedureCompetencies;

/**
 *
 * @author ALEX
 */
public class GuiProcedureCompetencies extends javax.swing.JFrame {
    Statement st;
    TableCompetencies competenze;
    TableProcedure procedure;
    TableProcedureCompetencies competenze_procedure;
    /**
     * Creates new form GuiProcedureCompetencies
     */
    public GuiProcedureCompetencies(Statement st) {
        initComponents();
        this.st = st;
        competenze = new TableCompetencies(st);
        procedure = new TableProcedure(st);
        competenze_procedure = new TableProcedureCompetencies(st);
        visualizzaCompetenze();
        visualizzaProcedure();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu = new javax.swing.JButton();
        jAddComp = new javax.swing.JButton();
        jRemoveCo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProcedure = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCompe = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCompProc = new javax.swing.JList<>();
        jLabelProced = new javax.swing.JLabel();
        jLabelCompe = new javax.swing.JLabel();
        jLabelCompSel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jAddComp.setText("Add competencies");
        jAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddCompActionPerformed(evt);
            }
        });

        jRemoveCo.setText("Remove competencies");
        jRemoveCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveCoActionPerformed(evt);
            }
        });

        jListProcedure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProcedureMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProcedure);

        jListCompe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCompeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListCompe);

        jListCompProc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCompProcMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListCompProc);

        jLabelProced.setText("Procedure list");

        jLabelCompe.setText("Competencies list");

        jLabelCompSel.setText("Competencies of the selected procedure ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMenu))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAddComp)
                                .addGap(58, 58, 58)
                                .addComponent(jRemoveCo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCompSel)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelProced)
                        .addGap(184, 184, 184)
                        .addComponent(jLabelCompe)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProced)
                    .addComponent(jLabelCompe)
                    .addComponent(jLabelCompSel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMenu)
                    .addComponent(jAddComp)
                    .addComponent(jRemoveCo))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String selectedComp;
String selectedProced;
    private void jRemoveCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveCoActionPerformed
        String competenza = jListCompProc.getSelectedValue();
        if(competenza == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected a competencies?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        deleteAssign(competenza);
    }//GEN-LAST:event_jRemoveCoActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuActionPerformed

    private void jAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddCompActionPerformed
        if (selectedComp == null && selectedProced == null) {
            JOptionPane.showMessageDialog(null, "Please select an procedure's identifier and a competence.");
            return;
        }
        if (selectedComp == null) {
            JOptionPane.showMessageDialog(null,"Please select a competence." );
            return;
        }
        if (selectedProced == null) {
            JOptionPane.showMessageDialog(null,"Please select an procedure's identifier." );
            return;
        }
        insertAssign(selectedComp,selectedProced);
    }//GEN-LAST:event_jAddCompActionPerformed

    private void jListProcedureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProcedureMouseClicked
        selectedProced = jListProcedure.getSelectedValue();
        visualizzaCompetenzeProcedure(selectedProced);
        if(selectedProced == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected a procedure?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jListProcedureMouseClicked

    private void jListCompeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCompeMouseClicked
        selectedComp = jListCompe.getSelectedValue();
        if(selectedComp == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected a competencies?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListCompeMouseClicked

    private void jListCompProcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCompProcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListCompProcMouseClicked

    private void visualizzaCompetenze() {
        String[] compet = competenze.visualizeCompetencies();
        jListCompe.setListData(compet);
    }

    private void visualizzaProcedure() {
        String[] proced = procedure.visualizeProcedure();
        jListProcedure.setListData(proced);
    }
    
    private void visualizzaCompetenzeProcedure(String selectedProced){
        String[] comp_proc = competenze_procedure.visualizeCompetencies(selectedProced);
        jListCompProc.setListData(comp_proc);
        
    }
    
    private void insertAssign(String comp, String proced){
        if(competenze_procedure.insertCompToProced(comp, proced))
            visualizzaCompetenzeProcedure(selectedProced);
        else
            JOptionPane.showMessageDialog(null,"Competence already added for this procedure");
    }
    private void deleteAssign(String competenza){
        
        if(competenze_procedure.delete(competenza))
            visualizzaCompetenzeProcedure(selectedProced);
        else
            JOptionPane.showMessageDialog(null,"ERROR");
    }

    /*private void visualizzaCompetenzeAttività(String attività) {
        String[] competenze = competenzeAttività.visualizeCompetencies(attività);
        jListActComp.setListData(competenze);
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiProcedureCompetencies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddComp;
    private javax.swing.JLabel jLabelCompSel;
    private javax.swing.JLabel jLabelCompe;
    private javax.swing.JLabel jLabelProced;
    private javax.swing.JList<String> jListCompProc;
    private javax.swing.JList<String> jListCompe;
    private javax.swing.JList<String> jListProcedure;
    private javax.swing.JButton jMenu;
    private javax.swing.JButton jRemoveCo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
