/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage;

import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tablepackage.TableProcedure;

/**
 *
 * @author ALEX
 */
public class GuiProcedureManagement extends javax.swing.JFrame {
    private Statement st;
    private TableProcedure proced;
    public GuiProcedureManagement(Statement st) {
        initComponents();
        this.st = st;
        proced = new TableProcedure(st);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jNameField = new javax.swing.JTextField();
        jUrlField = new javax.swing.JTextField();
        jInsert = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jVisualize = new javax.swing.JButton();
        jInfo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProcedure = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procedure Management");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(162, 197, 220));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/1f4c1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jNameField.setBackground(new java.awt.Color(213, 234, 255));
        jNameField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jNameField.setForeground(new java.awt.Color(46, 92, 137));
        jNameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameFieldActionPerformed(evt);
            }
        });

        jUrlField.setBackground(new java.awt.Color(213, 234, 255));
        jUrlField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jUrlField.setForeground(new java.awt.Color(46, 92, 137));
        jUrlField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUrlField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUrlFieldMouseClicked(evt);
            }
        });
        jUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUrlFieldActionPerformed(evt);
            }
        });

        jInsert.setBackground(new java.awt.Color(141, 199, 228));
        jInsert.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jInsert.setForeground(new java.awt.Color(34, 102, 136));
        jInsert.setText("INSERT");
        jInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertActionPerformed(evt);
            }
        });

        jDelete.setBackground(new java.awt.Color(141, 199, 228));
        jDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jDelete.setForeground(new java.awt.Color(34, 102, 136));
        jDelete.setText("DELETE");
        jDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jUpdate.setBackground(new java.awt.Color(141, 199, 228));
        jUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jUpdate.setForeground(new java.awt.Color(34, 102, 136));
        jUpdate.setText("UPDATE");
        jUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jVisualize.setBackground(new java.awt.Color(141, 199, 228));
        jVisualize.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jVisualize.setForeground(new java.awt.Color(34, 102, 136));
        jVisualize.setText("VISUALIZE");
        jVisualize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jVisualize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisualizeActionPerformed(evt);
            }
        });

        jInfo.setBackground(new java.awt.Color(141, 199, 228));
        jInfo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jInfo.setForeground(new java.awt.Color(34, 102, 136));
        jInfo.setText("INFO");
        jInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInfoActionPerformed(evt);
            }
        });

        jListProcedure.setBackground(new java.awt.Color(213, 234, 255));
        jListProcedure.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListProcedure.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jListProcedure.setForeground(new java.awt.Color(46, 92, 137));
        jListProcedure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProcedureMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListProcedure);

        jPanel2.setBackground(new java.awt.Color(141, 199, 228));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 64, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(141, 199, 228));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 64, 82));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("URL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jVisualize, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVisualize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUrlFieldActionPerformed

    private void jNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameFieldActionPerformed

    private void jInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertActionPerformed
        if(jNameField.getText().isEmpty() || jUrlField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Insert all fields.");
        }
        else{
            String name = jNameField.getText().trim();
            String url = jUrlField.getText().trim();
            inserimentoProcedura(name,url);
            jNameField.setText("");
            jUrlField.setText("");
            
        }
    }//GEN-LAST:event_jInsertActionPerformed

    private void jInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInfoActionPerformed
        JOptionPane.showMessageDialog(null, "Remember. To be able to insert a new procedure, the URL relating to the Google Drive(or another service) shared folder must be entered in the URL field.","Insert_Procedure", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jInfoActionPerformed

    private void jVisualizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisualizeActionPerformed
        jNameField.setText("");
        jUrlField.setText("");
        visualizzaListaProcedure();
        
    }//GEN-LAST:event_jVisualizeActionPerformed
    private String nameSelected;
    private String urlSelected;
    private void jListProcedureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProcedureMouseClicked
        nameSelected = jListProcedure.getSelectedValue();
        jNameField.setText(nameSelected);
        urlSelected = proced.getUrl(nameSelected);
        jUrlField.setText(urlSelected);
        
    }//GEN-LAST:event_jListProcedureMouseClicked

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        
        
        if(jNameField.getText().isEmpty() || jUrlField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please select an item from the list first.");
        }
        else{
            String name = jNameField.getText().trim();
            deleteProcedure(name);
            jNameField.setText("");
            jUrlField.setText("");
            visualizzaListaProcedure();
        }
        
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        
        
        
        if(jNameField.getText().isEmpty() || jUrlField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please select an item from the list first");
            visualizzaListaProcedure();
        }
        else{
            String newname = jNameField.getText();
            String url = jUrlField.getText();
            if(newname.equals(nameSelected) && url.equals(urlSelected)){
                JOptionPane.showMessageDialog(null,"No update maded.");
                jNameField.setText("");
                jUrlField.setText("");
                
            }
            else{
                updateProcedura(newname,url,nameSelected);
                visualizzaListaProcedure();
            }
        }
           
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jUrlFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUrlFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jUrlFieldMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String url = jUrlField.getText();
        try {
            URL uri = new URL(url);
            Desktop.getDesktop().browse(uri.toURI());
            //La classe Desktop ha un costruttore privato, e per questo viene istanziato tramite il suo metodo static sync getDestkop().
            //Una volta istanziato l'oggetto, possiamo chiamare la funzione browse che ci permette di lanciare il nostro browser di default.
            //Il metodo browse vuole un oggetto di tipo URI, ottenibile grazie al metodo toURI di URL.
            // new URL(url) prende la stringa e la converte in URL e se fallisce lancia l'eccezione MalformedURLException.
            // il metodo toURI (Uniform Resource Identifier) converte il corrispettivo URL in URI e lancia, se fallisce, l'eccezione URISyntaxException.
        } catch (MalformedURLException ex) {
            //by new URL(url) - Questa eccezione è lanciata se non viene specificato alcun protocollo, o viene trovato un protocollo sconosciuto o la specifica(url nel nostro caso) è nulla 
            Logger.getLogger(GuiProcedureManagement.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Unspecified or incorrect protocol or missing URL.","Malformed",JOptionPane.ERROR_MESSAGE);
        } catch (URISyntaxException ex) {
            //by toURI() - Questa eccezione è lanciata nel caso in cui l'URL non è formattato rigorosamente secondo RFC2396 e non può essere convertito in un URI.
            Logger.getLogger(GuiProcedureManagement.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"URL not formatted correctly according to RFC2396","URISyntax.",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            //by browse() - Lancia un eccezione se il browser di default non è stato trovato o ha fallito nel lanciare il browser stesso.
            Logger.getLogger(GuiProcedureManagement.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Default browser not found or browser launch failed.","BrowserError",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        new GuiMenuAdmin(st).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void inserimentoProcedura(String name, String url){
       
        if(proced.insertProcedure(name, url) == true){
            JOptionPane.showMessageDialog(null, "Successful insertion");
            }
        else{
            JOptionPane.showMessageDialog(null, "Ops,something went wrong?");
            }
    }
    
    private void updateProcedura(String newname,String url, String oldname){
        
        if(proced.updateProcedure(newname, url, oldname))
            JOptionPane.showMessageDialog(null,"Successful update");
        else
            JOptionPane.showMessageDialog(null, "Ops,something went wrong?");
    }
    
    private void visualizzaListaProcedure() {
        
            String[] procedure;
            procedure = proced.visualizeProcedure();
            jListProcedure.setListData(procedure);
    }
    
    private void deleteProcedure(String name){
        
        
        if(proced.deleteProcedure(name) == true){
            JOptionPane.showMessageDialog(null, "Successful deletion");
            }
        else{
            JOptionPane.showMessageDialog(null, "Ops,something went wrong?");
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiProcedureManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jInfo;
    private javax.swing.JButton jInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListProcedure;
    private javax.swing.JTextField jNameField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jUpdate;
    private javax.swing.JTextField jUrlField;
    private javax.swing.JButton jVisualize;
    // End of variables declaration//GEN-END:variables
}
