/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage;

import java.sql.Statement;
import javax.swing.JOptionPane;
import tablepackage.TableMaintenanceActivities;
import tablepackage.TableProcedure;
import tablepackage.TableProcedureActivity;

/**
 *
 * @author ALEX
 */
public class GuiProcedureActivities extends javax.swing.JFrame {
Statement st;
TableMaintenanceActivities activity;
TableProcedure procedure;
TableProcedureActivity procedure_attività;
    /**
     * Creates new form GuiProcedureActivities
     */
    public GuiProcedureActivities(Statement st) {
        initComponents();
        activity = new TableMaintenanceActivities(st);
        procedure = new TableProcedure(st);
        procedure_attività = new TableProcedureActivity(st);
        visualizzaAttività();
        visualizzaProcedura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAct = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProc = new javax.swing.JList<>();
        jMenu = new javax.swing.JButton();
        jAddPro = new javax.swing.JButton();
        jRemoveProc = new javax.swing.JButton();
        jTextFieldProcAc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Activities list");

        jLabel2.setText("Procedure list");

        jLabel3.setText("Procedure of activities list");

        jListAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListActMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListAct);

        jListProc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProcMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListProc);

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jAddPro.setText("Add procedure");
        jAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddProActionPerformed(evt);
            }
        });

        jRemoveProc.setText("Remove procedure");
        jRemoveProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveProcActionPerformed(evt);
            }
        });

        jTextFieldProcAc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldProcAcMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jMenu))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jRemoveProc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextFieldProcAc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jAddPro))))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldProcAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMenu)
                    .addComponent(jAddPro)
                    .addComponent(jRemoveProc))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String selectedActivity;
String selectedProcedure;
    private void jListActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListActMouseClicked
        selectedActivity = jListAct.getSelectedValue();
        String dati = activity.visualizeActivity(selectedActivity);
        visualizzaProcedureAttività(selectedActivity);
        if (selectedActivity != null) {
            JOptionPane.showMessageDialog(null, dati);
        } else {
            JOptionPane.showMessageDialog(null, "Activity not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListActMouseClicked

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuActionPerformed

    private void jListProcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProcMouseClicked
        selectedProcedure = jListProc.getSelectedValue();
        if(selectedProcedure == null)
            JOptionPane.showMessageDialog(null,"Procedure not found","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jListProcMouseClicked

    private void jAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddProActionPerformed
         if (selectedActivity == null && selectedProcedure == null) {
            JOptionPane.showMessageDialog(null, "Please select an activity's identifier and a procedure.");
            return;
        }
        if (selectedActivity == null) {
            JOptionPane.showMessageDialog(null,"Please select an activity." );
            return;
        }
        if (selectedProcedure == null) {
            JOptionPane.showMessageDialog(null,"Please select an procedure's name." );
            return;
        }
        insertAssign(selectedActivity,selectedProcedure);
    }//GEN-LAST:event_jAddProActionPerformed

    private void jRemoveProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveProcActionPerformed
        String attività = jListAct.getSelectedValue();
        if(attività == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected an activity?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        deleteAssign(attività);
    }//GEN-LAST:event_jRemoveProcActionPerformed

    private void jTextFieldProcAcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldProcAcMouseClicked
        jTextFieldProcAc.setEditable(false);
    }//GEN-LAST:event_jTextFieldProcAcMouseClicked

    
    private void visualizzaAttività() {
        String[] attività = activity.visualizeActivities();
        jListAct.setListData(attività);
    }
    
    private void visualizzaProcedura() {
        String[] procedura = procedure.visualizeProcedure();
        jListProc.setListData(procedura);
    }
    
    private void visualizzaProcedureAttività(String selectedAct){
        String[] proc_act = procedure_attività.visualizeProcedure(selectedAct);
        jTextFieldProcAc.setText(proc_act[0]);
        
    }
    
     private void insertAssign(String actitivy, String proced){
        if(procedure_attività.insertProcToAct(actitivy, proced))
            visualizzaProcedureAttività(selectedProcedure);
        else
            JOptionPane.showMessageDialog(null,"Procedure already added for this activity or another activity");
    }
     private void deleteAssign(String activity){
        
        if(procedure_attività.delete(activity))
            visualizzaProcedureAttività(selectedProcedure);
        else
            JOptionPane.showMessageDialog(null,"ERROR");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiProcedureActivities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListAct;
    private javax.swing.JList<String> jListProc;
    private javax.swing.JButton jMenu;
    private javax.swing.JButton jRemoveProc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldProcAc;
    // End of variables declaration//GEN-END:variables
}
