/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipackage;

import java.sql.Statement;
import javax.swing.JOptionPane;
import tablepackage.TableCompetencies;
import tablepackage.TableProcedure;
import tablepackage.TableProcedureCompetencies;

/**
 *
 * @author ALEX
 */
public class GuiProcedureCompetencies extends javax.swing.JFrame {
    Statement st;
    TableCompetencies competenze;
    TableProcedure procedure;
    TableProcedureCompetencies competenze_procedure;
    /**
     * Creates new form GuiProcedureCompetencies
     */
    public GuiProcedureCompetencies(Statement st) {
        initComponents();
        this.st = st;
        competenze = new TableCompetencies(st);
        procedure = new TableProcedure(st);
        competenze_procedure = new TableProcedureCompetencies(st);
        visualizzaCompetenze();
        visualizzaProcedure();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRemoveCo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProcedure = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCompe = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCompProc = new javax.swing.JList<>();
        jAddComp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelProced = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCompe = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelCompSel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROCEDURES' COMPETENCIES MANAGEMENT");
        setBackground(new java.awt.Color(162, 197, 220));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(162, 197, 220));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRemoveCo.setBackground(new java.awt.Color(141, 199, 228));
        jRemoveCo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRemoveCo.setForeground(new java.awt.Color(34, 102, 136));
        jRemoveCo.setText("REMOVE COMPETENCE");
        jRemoveCo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRemoveCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveCoActionPerformed(evt);
            }
        });

        jListProcedure.setBackground(new java.awt.Color(213, 234, 255));
        jListProcedure.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListProcedure.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jListProcedure.setForeground(new java.awt.Color(46, 92, 137));
        jListProcedure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProcedureMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProcedure);

        jListCompe.setBackground(new java.awt.Color(213, 234, 255));
        jListCompe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListCompe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jListCompe.setForeground(new java.awt.Color(46, 92, 137));
        jListCompe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCompeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListCompe);

        jListCompProc.setBackground(new java.awt.Color(213, 234, 255));
        jListCompProc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListCompProc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jListCompProc.setForeground(new java.awt.Color(46, 92, 137));
        jListCompProc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCompProcMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListCompProc);

        jAddComp.setBackground(new java.awt.Color(141, 199, 228));
        jAddComp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jAddComp.setForeground(new java.awt.Color(34, 102, 136));
        jAddComp.setText("ADD COMPETENCE");
        jAddComp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddCompActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(141, 199, 228));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelProced.setBackground(new java.awt.Color(27, 64, 82));
        jLabelProced.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelProced.setForeground(new java.awt.Color(27, 64, 82));
        jLabelProced.setText("Procedure list");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProced)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProced)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(141, 199, 228));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCompe.setBackground(new java.awt.Color(27, 64, 82));
        jLabelCompe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCompe.setForeground(new java.awt.Color(27, 64, 82));
        jLabelCompe.setText("Competencies list");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabelCompe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCompe)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(141, 199, 228));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCompSel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCompSel.setForeground(new java.awt.Color(27, 64, 82));
        jLabelCompSel.setText("Competencies of the selected procedure ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCompSel)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompSel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jAddComp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jRemoveCo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAddComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRemoveCo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String selectedComp;
String selectedProced;
    private void jRemoveCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveCoActionPerformed
        String competenza = jListCompProc.getSelectedValue();
        if(competenza == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected a competencies?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        deleteAssign(competenza);
    }//GEN-LAST:event_jRemoveCoActionPerformed

    private void jAddCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddCompActionPerformed
        if (selectedComp == null && selectedProced == null) {
            JOptionPane.showMessageDialog(null, "Please select an procedure's identifier and a competence.");
            return;
        }
        if (selectedComp == null) {
            JOptionPane.showMessageDialog(null,"Please select a competence." );
            return;
        }
        if (selectedProced == null) {
            JOptionPane.showMessageDialog(null,"Please select an procedure's identifier." );
            return;
        }
        insertAssign(selectedComp,selectedProced);
    }//GEN-LAST:event_jAddCompActionPerformed

    private void jListProcedureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProcedureMouseClicked
        selectedProced = jListProcedure.getSelectedValue();
        visualizzaCompetenzeProcedure(selectedProced);
        if(selectedProced == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected a procedure?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jListProcedureMouseClicked

    private void jListCompeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCompeMouseClicked
        selectedComp = jListCompe.getSelectedValue();
        if(selectedComp == null){
            JOptionPane.showMessageDialog(null,"Oops, have you selected a competencies?","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListCompeMouseClicked

    private void jListCompProcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCompProcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListCompProcMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       this.setVisible(false);
       new GuiMenuAdmin(st).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void visualizzaCompetenze() {
        String[] compet = competenze.visualizeCompetencies();
        jListCompe.setListData(compet);
    }

    private void visualizzaProcedure() {
        String[] proced = procedure.visualizeProcedure();
        jListProcedure.setListData(proced);
    }
    
    private void visualizzaCompetenzeProcedure(String selectedProced){
        String[] comp_proc = competenze_procedure.visualizeCompetencies(selectedProced);
        jListCompProc.setListData(comp_proc);
        
    }
    
    private void insertAssign(String comp, String proced){
        if(competenze_procedure.insertCompToProced(comp, proced))
            visualizzaCompetenzeProcedure(selectedProced);
        else
            JOptionPane.showMessageDialog(null,"Competence already added for this procedure");
    }
    private void deleteAssign(String competenza){
        
        if(competenze_procedure.delete(competenza))
            visualizzaCompetenzeProcedure(selectedProced);
        else
            JOptionPane.showMessageDialog(null,"ERROR");
    }

    /*private void visualizzaCompetenzeAttività(String attività) {
        String[] competenze = competenzeAttività.visualizeCompetencies(attività);
        jListActComp.setListData(competenze);
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProcedureCompetencies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiProcedureCompetencies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddComp;
    private javax.swing.JLabel jLabelCompSel;
    private javax.swing.JLabel jLabelCompe;
    private javax.swing.JLabel jLabelProced;
    private javax.swing.JList<String> jListCompProc;
    private javax.swing.JList<String> jListCompe;
    private javax.swing.JList<String> jListProcedure;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jRemoveCo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
